apiVersion: v1
kind: Pod
metadata:
  name: pod4
spec:
  containers:
    - name: web
      image: nginx:latest
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 3
        periodSeconds: 3
  nodeName: kube-master
  tolerations:
        - key: "node-role.kubernetes.io/master"
          effect: "NoSchedule"
          operator: "Exists"
